

INSERT INTO locations (name, description, state_id) VALUES
('WAL MART', 'SUPERAMA ', 15),
('SORIANA', 'GUADALAJARA', 14),
('WAL MART', 'CHALCO BAE', 15),
('WAL MART', 'CHALCO', 15),
('Walmart Prueba', 'Gomez Palacio', 10),
('Walmart Prueba 3', 'Destino Prueba', 99),
('Walmart Prueba 4', 'Destino Prueba 2', 99),
('Walmart Prueba 5', 'Destino Chiapas', 5),
('WAL MART 1', 'Candelaria', 4),
('Walmart', 'Iztapalapa', 9),
('Walmart', 'Benito Juarez', 9),
('Soriana', 'Benito Juarez', 9),
('Soriana', 'Ensenada', 2),
('Soriana', 'Patzcuaro', 16),
('WALMART', 'Cuautitlan', 15),
('WALMART', 'Monterrey', 19),
('NORTE/SUPERAMA', 'Cuautitlan', 15),
('Walmart Prueba 6', 'Cosio', 1),
('Walmart Prueba 7', 'Destino Prueba X', 6),
('Walmart Prueba 8', 'Destino Prueba XX', 6),
('planta', 'alvaro Obregon', 9),
('Walmart', 'Nativitas', 29),
('SORIANA', 'ACAMBARO', 21),
('PLANTA HALCON', 'Mulege', 3),
('Walmart', 'Los Cabos', 3),
('DESARROLLO COMERCIAL ABARROTERO', 'Tlajomulco de Zu', 14),
('EXPORTADORA DE SAL, SA DE CV', 'Mulege', 3),
('WAL MART', 'Culiacan', 25),
('SORIANA', 'Tultitlan', 15),
('SORIANA ALM. CTRL.', 'Tultitlan', 15),
('MX20', 'Tultitlan', 15),
('NUEVO MILENIO', 'Tlalpan', 9),
('MITSA', 'Teoloyucan', 15),
('AVP FASKE', 'Queretaro', 22),
('SORIANA', 'Pedro Escobedo', 22),
('OPERADORA MERCO SA DE CV', 'Apodaca', 19),
('WAL MART', 'Monterrey', 19),
('CROSS DOCK', 'Monterrey', 19),
('SAHUAYO', 'Monterrey', 19),
('WAL MART', 'VILLAHERMOSA', 27),
('SAN LUCAS TEPEMAJALCO', 'Toluca', 15),
('SERVICIO COMERCIAL GARIS SA DE CV', 'SAN LUCAS TEPEMAJALCO', 15),
('DESARROLLO COMERCIAL ABARROTERO SA', 'Aguascalientes', 1),
('SERV. COMER. GARIS, SA', 'Metepec', 15),
('SAHUAYO', 'S.L.P.', 24),
('SERVICIO COMERCIAL GARIS, SA DE CV', 'SANTIAGO DE QUERETARO', 22),
('SAHUAYO', 'Aguascalientes', 1),
('ABARROTERA DEL DUERO, SA DE CV', 'Morelia', 16),
('ABARROTERA DEL DUERO SA DE CV', 'San Luis Potosi', 24),
('CADENA COMERCIAL OXXO SA DE CV', 'Leon', 11),
('SAHUAYO', 'Altamira', 28),
('CROSS DOCK', 'Guadalajara', 14),
('FRUTERIA WELTON SA DE CV', 'San Luis Rio Colorado', 26),
('SORIANA', 'Tultitlan', 15),
('MX32', 'Guanajuato', 11),
('SAHUAYO', 'GDL, STA. ANITA', 14),
('ABARROTES ABEJA, SA DE CV', 'Zapopan', 14),
('ABARROTES ABEJA, SA DE CV', 'Guadalajara', 14),
('Walmart Prueba 9', 'Bahia de Banderas', 18),
('DESARROLLO COMERCIAL ABARROTERO SA', 'Cortazar', 11),
('SAHUAYO', 'Celaya', 11),
('SUPER ABARROTES LUPITA SA DE CV', 'Guadalajara', 14),
('CHEDRAUI', 'Guadalajara', 14),
('WAL MART', 'STA BARBARA NAVE 1', 15),
('WAL MART', 'STA BARBARA NAVE 2', 99),
('SAHUAYO', 'TLALNEPANTLA', 15),
('SCORPION DISTRIBUIDOR', 'Tultitlan', 15),
('WAL MART', 'NORTE', 15),
('WAL MART', 'SUR', 15),
('WAL MART', 'SUPERAMA', 15),
('SORIANA', 'Monterrey', 19),
('ALMACENES IBARRA, SA DE CV', 'Reynosa', 28),
('DISTRIBUIDORA DE VIVERES, SA', 'CD. VICTORIA', 28),
('CENTRO COMERCIAL GUAJARDO SA DE CV', 'Reynosa', 28),
('MX28', 'Mexicali', 2),
('CASA LEY, SA. DE CV.', 'Culiacan', 25),
('ABARROTERA DEL DUERO, SA DE CV', 'Ahome', 25),
('MAS BODEGA Y LOGISTICA SA DE CV', 'Hermosillo', 26),
('MX21', 'Queretaro', 22),
('MX45', 'CARVAJAL', 11),
('CHEDRAUI', 'VILLAHERMOSA', 27),
('WAL MART', 'Monterrey', 19),
('WAL MART', 'MONTERREY BAE', 19),
('SAHUAYO', 'Chihuahua', 6),
('WAL MART', 'MONTERREY BAE', 19),
('SAHUAYO', 'Chihuahua', 6),
('MAS BODEGA Y LOGISTICA SA DE CV', 'Guadalupe', 19),
('DECASA DEL CENTRO SA DE CV', 'Torreon', 7),
('CROSS DOCK', 'Chihuahua', 6),
('ISSSTE', 'Tampico', 28),
('GARIS', 'Toluca', 15),
('ABARROTERA DEL DUERO, SA DE CV', 'Lazaro Cardenas', 16),
('TORRES CONSTRUALIMENTOS', 'ZACATIPAN', 24),
('ABARROTERA DEL DUERO, SA DE CV', 'Zamora', 16),
('GARIS', 'Tenancingo', 15),
('ABARROTES SAN FERNANDO', 'Leon', 11),
('ABARROTES, SA DE CV', 'CD. MANTE', 28),
('EL SITIO ABARROTES, SA DE CV', 'San Luis Potosi', 24),
('SAHUAYO', 'Morelia', 16),
('ALMACENES IBARRA, SA DE CV', 'Altamira', 28),
('ISSSTE', 'Toluca', 15),
('PRODUCTOS DE CONSUMO Z SA DE CV', 'Tijuana', 2),
('SAHUAYO', 'Tijuana', 2),
('MX28', 'Mexicali', 2),
('MAS BODEGA Y LOGISTICA SA DE CV', 'Tijuana', 2),
('WAL MART', 'NORTE', 15),
('SORIANA ALM. CTRL.', 'Tultitlan', 15),
('FARMACIAS GUADALAJARA', 'Tonala', 14),
('WAL MART', 'SUPERAMA ', 15),
('WAL MART', 'SUR', 15),
('FRUTERIA WELTON SA DE CV', 'San Luis Rio Colorado', 26),
('MITSA', 'Teoloyucan', 15),
('ABARROTERA DEL DUERO SA DE CV', 'Guadalajara', 14),
('DESARROLLO COMERCIAL ABARROTERO', 'TLAJOMULCO DE ZUÑIGA', 14),
('COMERCIAL DE ABARROTERAS GDL', 'Tonala', 14),
('PRODUCTOS DE CONSUMO Z', 'Guadalajara', 14),
('H.E.B. CENTRO DE DISTRIBUCION', 'Monterrey', 19),
('WAL MART', 'BAE', 15),
('SAHUAYO', 'Monterrey', 19),
('FARMACIAS BENAVIDES', 'Monterrey', 19),
('SORIANA', 'Queretaro', 22),
('OPERADORA CD. JUAREZ', 'CD. JUAREZ', 6),
('ABARROTES MENDEZ', 'Fresnillo', 32),
('ISSSTE', 'Fresnillo', 32),
('ISSSTE', 'Zacatecas', 32),
('TIENDAS GARCES, SA DE CV', 'Toluca', 15),
('ABARROTERA DEL DUERO, SA DE CV', 'Uruapan', 16),
('WAL MART', 'SUR', 15),
('ABASTECEDORA  DE ABARROTES SCORPION', 'Cuautitlan', 15),
('COMERCIAL E IMPORTADORA SONORENSE', 'CD. OBREGON', 26),
('FRUTERIA CUAUHTEMOC, SA DE CV', 'Cuauhtemoc', 6),
('LA ECONOMICA DE ABASTOS', 'CD. JUAREZ', 6),
('ABASTECEDORA COMERCIAL DE PARRAL', 'Hidalgo del Parral', 6),
('SUPERMERCADOS ORGANIZADOS SA DE CV', 'Hermosillo', 26),
('WAL MART', 'SUPERAMA/NORTE', 15),
('WAL MART', 'STA BARBARA NAVE 2', 15),
('SAM´S', 'Culiacan', 25),
('SAM´S', 'VILLAHERMOSA', 27),
('SAM´S', 'Monterrey', 19),
('CITY CLUB', 'Guadalajara', 14),
('CITY CLUB', 'Monterrey', 19),
('SAM´S', 'Culiacan', 25),
('SAM´S', 'Culiacan', 25),
('MegaJanga', 'Yanga', 30),
('FARMACIA GUADALAJARA', 'Tonala', 14),
('FARMACIA GUADALAJARA', 'El Salto', 14),
('SORIANA ALM. CTRL.', 'Guadalajara', 14),
('PATIOS SLIASA', 'CD HIDALGO', 5),
('TRANSPORTES MONROY', 'CD HIDALGO', 5),
('TRANSPORTES MONTERREY (MZ)', 'Manzanillo', 8),
('TRANSPORTES MONTERREY (VER)', 'Veracruz', 30),
('PATIOS ANCIRA', 'Nuevo Laredo', 28),
('PATIOS FEMA', 'Nuevo Laredo', 28),
('PATIOS MET', 'Nuevo Laredo', 28),
('PATIOS MORALES', 'Nuevo Laredo', 28),
('PATIOS ROGER', 'Nuevo Laredo', 28),
('PATIOS TNIR', 'Nuevo Laredo', 28),
('PATIOS VIA EXPRESS', 'Nuevo Laredo', 28),
('Destino de prueba XY', 'Atoyac de alvarez', 12),
('WAL MART', 'NORTE', 15),
('WAL MART', 'BAE', 15),
('CASA LEY PERFUMERIA', 'Culiacan', 25),
('PRODUCTOS DE CONSUMO Z SA DE CV', 'Tijuana', 2),
('Destino de prueba YX', 'Navolato', 25),
('Destino de prueba MM', 'Atlangatepec', 29),
('Destino de prueba AA', 'Cedral', 24),
('WAL MART', 'Guadalajara', 14),
('DISTRIBUIDORA HUGO´S SA DE CV', 'Guadalajara', 14),
('FARMACIAS BENAVIDES', 'Monterrey', 19),
('OPERADORA REYNOSA', 'Monterrey', 19),
('SAHUAYO', 'GDL, STA. ANITA', 14),
('REPRESENTACIONES J.M.P. SA DE CV', 'Guadalajara', 14),
('SORIANA ALMACEN CENTRAL', 'Guadalajara', 14),
('SORIANA', 'Tultitlan', 15),
('H.E.B. CENTRO DE DISTRIBUCION', 'Monterrey', 19),
('CHEDRAUI', 'Monterrey', 19),
('NADRO', 'Guadalajara', 14),
('OPERADORA REYNOSA', 'Monterrey', 19),
('H.E.B. CENTRO DE DISTRIBUCION', 'General Escobedo', 19),
('SORIANA.COM', 'Monterrey', 19),
('GUADALAJARA BAE', 'Guadalajara', 14),
('ABARROTERA DEL DUERO, SA DE CV', 'Tlaquepaque', 14),
('Patios Medrano Chiapas', 'Cd Hidalgo', 5),
('DECASA', 'TLAJOMULCO', 14),
('WAL MART', 'SUPERAMA', 15),
('SORIANA', 'Monterrey', 19),
('SORIANA', 'Tultitlan', 15),
('ALMACEN CENTRAL', 'Guadalajara', 14),
('OPERADORA MERCO SA DE CV', 'Apodaca', 19),
('DESARROLLO COMERCIAL ABARROTERO', 'TLAJOMULCO DE ZUÑIGA', 14),
('PRODUCTOS DE CONSUMO Z', 'Tlaquepaque', 14),
('SAM´S', 'OBISPO', 15),
('SERVICIO COMERCIAL GARIS, SA DE CV', 'Zitacuaro', 16),
('COSTCO', 'Tepeji del Rio de Ocampo', 13),
('COSTCO', 'Tepeji del Rio de Ocampo', 13),
('SORIANA', 'Tultitlan', 15),
('ISSSTE', 'Zitacuaro', 16),
('TIENDA D.DESCUENTO ARTELI, SA DE CV', 'Altamira', 28),
('COM MEX', 'Tultitlan', 15),
('CROSS DOCK', 'Guadalajara', 14),
('CADENA COMERCIAL OXXO, SA DE CV', 'Monterrey', 19),
('OBISPO', 'Cuautitlan Izcalli', 15),
('OBISPO', 'SAM´S ', 15),
('GUADALAJARA', 'SAM´S ', 14),
('SAM´S ', 'VILLAHERMOSA', 27),
('OBISPO', 'SAM´S ', 15),
('TIENDAS CHEDRAUI SA DE CV', 'EL SALTO', 14),
('CITY CLUB', 'Monterrey', 19),
('CITY CLUB', 'Tultitlan', 15),
('ORGANIZACION SAHUAYO SA DE CV.', 'Tlajomulco de Zu', 14),
('Abarrotera del Duero SA de CV', 'Guadalajara', 14),
('SERV. COM. ALTAMIRANO, SA DE CV', 'Toluca', 15),
('SORIANA', 'Tultitlan', 15),
('WAL MART', 'Culiacan', 25),
('CASA LEY PERFUMERIA', 'Culiacan', 25),
('ALMACENES ZARAGOZA', 'Culiacan', 25),
('IMSS', 'CD MANTE', 28),
('IMSS', 'Aguascalientes', 1),
('ISSSTE', 'Guanajuato', 11),
('PRODUCTOS DE CONSUMO Z', 'Tlaquepaque', 14),
('ORGANIZACION SAHUAYO SA DE CV', 'San Luis Potosi', 24),
('CHEDRAUI', 'Teoloyucan', 15),
('CROSS DOCK', 'Monterrey', 19),
('CHEDRAUI', 'VILLAHERMOSA', 27),
('CHEDRAUI', 'Teoloyucan', 15),
('GRUPO ZORRO ABARROTERO', 'Toluca', 15),
('OPERADORA DE REYNOSA', 'BENITO JUAREZ', 19),
('IMSS', 'San Juan del Rio', 22),
('OPERADORA MERCO SA DE CV', 'Apodaca', 19),
('Mas Bodega y Logistica SA de CV', 'Guadalupe', 19),
('DESARROLLO COMERCIAL ABARROTERO', 'Huejotzingo', 21),
('UNIDAD COMERCIAL MAYOREO', 'Puebla', 21),
('SERVICIO COMER. GARIS, SA DE CV', 'Iztapalapa', 9),
('COM MEX', 'Tultitlan', 15),
('COMERCIAL E IMPORTADORA SONORENSE', 'ZAPOTE DEL VALLE', 14),
('MEDIMEX GDL S DE RL DE CV', 'Guadalajara', 14),
('ORGANIZACION SAHUAYO SA DE CV.', 'Tlajomulco de Zu', 14),
('ORGANIZACION SAHUAYO SA DE CV.', 'Celaya', 11),
('SORIANA ALMACEN CENTRAL', 'Tultitlan', 15),
('ALMACENES ZARAGOZA, SA de CV', 'Culiacan', 25),
('ABARROTERA DE VALLES, SA DE CV', 'Ciudad Valles', 24),
('Chedraui Centro de Distribucion 402', 'Zumpango', 15),
('Productos de Consumo Z SA de CV', 'Cuautitlan', 15),
('CROSS DOCK', 'Guadalajara', 14),
('CASA LEY, SA. de CV.', 'Culiacan', 25),
('FARMACIAS BENAVIDES SA B DE CV', 'Guadalupe', 19),
('HEMSA SA DE CV', 'Guadalupe', 19),
('SUPER MERCADOS DE ZAPOPAN SA DE CV', 'Zapopan', 14),
('Chedraui Centro de Distribucion 402', 'Teoloyucan', 15),
('DISTRIBUIDORA LOS AZUFRES SA DE CV', 'Zapopan', 14),
('OPERADORA DE REYNOSA SA DE CV', 'BENITO JUAREZ', 19),
('CASA LEY PERFUMERIA', 'Culiacan', 25),
('COSTCO', 'Tepeji del Rio de Ocampo', 13),
('ORGANIZACION SAHUAYO SA DE CV', 'Santa Catarina', 19),
('WALMART', 'SUR', 15),
('CROSS DOCK', 'Monterrey', 19),
('CASA LEY, SA. de CV.', 'Culiacan', 25),
('Mas Bodega y Logistica SA de CV', 'Guadalupe', 19),
('ORGANIZACION SAHUAYO SA DE CV', 'Santa Catarina', 19),
('ABARROTES ABEJA, SA DE CV', 'Zapopan', 14),
('SAM´S ', 'OBISPO', 15),
('CRISTAL BASICOS SA DE CV', 'Zapopan', 14),
('HEMSA SA DE CV', 'Monterrey', 19),
('OPERADORA DE REYNOSA', 'Monterrey', 19),
('SAM´S ', 'Guadalajara', 14),
('SAM´S ', 'Monterrey', 19),
('ORGANIZACION SAHUAYO SA DE CV', 'Santa Catarina', 19),
('STA BARBARA', 'SAM´S ', 15),
('DECASA', 'Guadalajara', 14),
('STA BARBARA', 'SAM´S ', 15),
('CASA LEY', 'Culiacan', 25),
('CROSS DOCK', 'Monterrey', 19),
('OPERADORA DE REYNOSA', 'Monterrey', 19),
('OXXO', 'Zapopan', 14),
('CITY CLUB', 'Monterrey', 19),
('CASA LEY PERFUMERÍA', 'Culiacan', 25);

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
